return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		branch = "master",
		lazy = false,
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = {
				"bash",
				"lua",
				"vim",
				"vimdoc",
				"html",
				"css",
				"javascript",
				"typescript",
				"python",
				"svelte",
				"solidity",
				"rust",
				"markdown",
				"markdown_inline",
				"graphql",
				"dockerfile",
				"yaml",
				"json",
			},
			sync_install = false,
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
		},
	},
}
